{
	"version": 1680542893,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-3.4.1.min.js",
		"offlineClient.js",
		"images/player-sheet0.png",
		"images/player-sheet1.png",
		"images/sprite-sheet0.png",
		"images/sprite2-sheet0.png",
		"images/sprite2-sheet1.png",
		"images/sprite2-sheet2.png",
		"images/sprite3-sheet0.png",
		"images/sprite3-sheet1.png",
		"images/sprite4-sheet0.png",
		"images/sprite5-sheet0.png",
		"images/tilemap.png",
		"images/sprite7-sheet0.png",
		"images/sprite8-sheet0.png",
		"images/sprite9-sheet0.png",
		"images/sprite10-sheet0.png",
		"images/sprite6-sheet0.png",
		"images/Новыйпроект-sheet0.png",
		"images/Новыйпроект2-sheet0.png",
		"images/sprite11-sheet0.png",
		"images/sprite12-sheet0.png",
		"images/sprite13-sheet0.png",
		"images/windowpopup-sheet0.png",
		"images/buttonplay-sheet0.png",
		"images/cloud-sheet0.png",
		"images/bigbutton-sheet0.png",
		"images/buttonmenu-sheet0.png",
		"images/Новыйпроект3-sheet0.png",
		"images/Ресурс-sheet0.png",
		"images/Ресурс2-sheet0.png",
		"images/Ресурс3-sheet0.png",
		"images/Ресурс4-sheet0.png",
		"images/Ресурс5-sheet0.png",
		"images/Ресурс6-sheet0.png",
		"images/Ресурс7-sheet0.png",
		"images/Ресурс8-sheet0.png",
		"images/cloud2-sheet0.png",
		"images/cloud3-sheet0.png",
		"images/light-sheet0.png",
		"images/windowlight-sheet0.png",
		"images/sprite14-sheet0.png",
		"images/sprite14-sheet1.png",
		"images/background-sheet0.png",
		"images/line-sheet0.png",
		"images/sprite15-sheet0.png",
		"images/sprite15-sheet1.png",
		"images/sprite15-sheet2.png",
		"media/shooter synthwave 8.ogg",
		"media/shooter synthwave 8.m4a",
		"media/shooter synthwave 7.ogg",
		"media/shooter synthwave 7.m4a",
		"media/shooter synthwave 6.ogg",
		"media/shooter synthwave 6.m4a",
		"media/shooter synthwave 5.ogg",
		"media/shooter synthwave 5.m4a",
		"media/shooter synthwave 4.ogg",
		"media/shooter synthwave 4.m4a",
		"media/shooter synthwave 3.ogg",
		"media/shooter synthwave 3.m4a",
		"media/shooter synthwave 2.ogg",
		"media/shooter synthwave 2.m4a",
		"media/shooter synthwave 1.ogg",
		"media/shooter synthwave 1.m4a",
		"media/(soft loop for dialogues, pause or other things) 9.ogg",
		"media/(soft loop for dialogues, pause or other things) 9.m4a",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png",
		"pathfind.js"
	]
}